package com.simulator.controller;

public enum SimulationTypes {
	SIMULATION_NOT_APPLICABLE,
	SIMULATION_GRID_MESH,
	SIMULATION_GRID_TORUS,
	SIMULATION_PACKETS_INTEREST, 
	SIMULATION_PACKETS_DATA,
	SUPRESSION_NO_PIT,
	SUPRESSION_ALREADY_SERVED,
	SUPRESSION_SENT_DATA_PACKET,
	SUPPRESS_FLOODING_FIB_HIT,
	SUPRESSION_PIT_ENTRY,
	SUPRESSION_DEST_NODE
}

