package com.simulator.enums;

public enum SimulationTypes {
	SIMULATION_NOT_APPLICABLE,
	SIMULATION_DISTRIBUTION_DEFAULT,
	SIMULATION_DISTRIBUTION_GLOBETRAFF,
	SIMULATION_DEBUGGING_OFF,
	SIMULATION_DEBUGGING_ON,
	SIMULATION_UNLIMITED_CACHESIZE,
	SIMULATION_LIMITED_CACHESIZE
}
