package com.simulator.enums;

public enum SimulationTypes {
	SIMULATION_NOT_APPLICABLE,
	SIMULATION_DISTRIBUTION_DEFAULT,
	SIMULATION_DISTRIBUTION_GLOBETRAFF,
	SIMULATION_DISTRIBUTION_GLOBETRAFF_LEAFNODE,
	SIMULATION_DISTRIBUTION_LEAFNODE,
	SIMULATION_DEBUGGING_OFF,
	SIMULATION_DEBUGGING_ON,
	SIMULATION_UNLIMITED_CACHESIZE,
	SIMULATION_LIMITED_CACHESIZE,
	SIMULATION_NO_CACHE,
	SIMULATION_CACHE,
	SIMULATION_SEG_ON,
	SIMULATION_SEG_OFF,
	SIMULATION_CACHE_FIB_TRACE_ON,
	SIMULATION_CACHE_FIB_TRACE_OFF,
	SIMULATION_CACHE_ENTRIES_ON,
	SIMULATION_CACHE_ENTRIES_OFF,
	SIMULATION_NO_FIB,
	SIMULATION_FIB
}
