package com.simulator.enums;

public enum SimulationTypes {
	SIMULATION_NOT_APPLICABLE,
	SIMULATION_GRID_MESH,
	SIMULATION_GRID_TORUS,
	SIMULATION_GRID_BRITE,
	SIMULATION_PACKETS_INTEREST, 
	SIMULATION_PACKETS_DATA,
	SIMULATION_DISTRIBUTION_DEFAULT,
	SIMULATION_DISTRIBUTION_GLOBETRAFF,
	SIMULATION_DEBUGGING_OFF,
	SIMULATION_DEBUGGING_ON,
	SIMULATION_UNLIMITED_CACHESIZE,
	SIMULATION_LIMITED_CACHESIZE,
	SUPRESSION_NO_PIT,
	SUPRESSION_ALREADY_SERVED,
	SUPRESSION_SENT_DATA_PACKET,
	SUPRESSION_FIB_ENTRY,
	SUPRESSION_PIT_ENTRY,
	SUPRESSION_DEST_NODE, 
	SUPPRESS_FLOODING_FIB_HIT
}
