package com.simulator.enums;

public enum SupressionTypes {
	SUPRESSION_NOT_APPLICABLE,
	SUPRESSION_NO_PIT,
	SUPRESSION_ALREADY_SERVED,
	SUPRESSION_SENT_DATA_PACKET,
	SUPRESSION_FIB_ENTRY,
	SUPRESSION_PIT_ENTRY,
	SUPRESSION_DEST_NODE, 
	SUPPRESS_FLOODING_FIB_HIT,
	SUPRESSION_FLOODING_PIT_HIT,
	PIT_EXPIRATION,
	EXHAUSTED_EXPIRATION_COUNT,
	INTEREST_TIME_OUT
}
