package com.simulator.enums;

public enum SupressionTypes {
	SUPRESSION_NOT_APPLICABLE,
	SUPRESSION_NO_PIT_INDEX,
	SUPRESSION_ALREADY_SERVED,
	SUPRESSION_SENT_DATA_PACKET,
	SUPRESSION_FIB_ENTRY,
	SUPRESSION_PIT_ENTRY,
	SUPRESSION_DEST_NODE, 
	FIB_HIT,
	PIT_HIT,
	PIT_EXPIRATION,
	EXHAUSTED_EXPIRATION_COUNT,
	INTEREST_TIME_OUT,
	SUPRESSION_NO_PIT_INDEX_DUE_PIT_EXPIRATION,
	REDUNDANT_PIT_HIT,
	SUPRESSION_NO_PIT_ENTRY_ORIGDPKT
}
